baseurl:
   microservice2: http://localhost:8082/
allowed :
  url : "http://localhost:3000,http://localhost:3001,http://localhost:8080,http://localhost:8081,http://localhost:8082,http://localhost:8083"
server:
  port: "8080"
spring:
  application:
    name: "Microservice1"
