---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-app
  template:
    metadata:
      labels:
        app: microservice-app
    spec:
      containers:
        - name: microservice1
          image: ashu20150/microservice1:1
          ports:
            - containerPort: 8080
          env:
            - name: BASEURL_MICROSERVICE2
              value: http://localhost:8082/
            - name : SPRING_PROFILES_ACTIVE
              value: dev 
            - name: SPRING_APPLICATION_JSON
              value: '{ "allowed": { "url": ["*"] } }'
        - name: microservice2
          image: ashu20150/microservice2:1
          ports:
            - containerPort: 8082
          env:
            - name : SPRING_PROFILES_ACTIVE
              value: dev 
            - name: SPRING_APPLICATION_JSON
              value: '{ "allowed": { "url": ["*"] } }'
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-app-service
spec:
  selector:
    app: microservice-app
  ports:
    - name: microservice1-http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: microservice2-http
      protocol: TCP
      port: 82
      targetPort: 8082
  type: LoadBalancer
