apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      containers:
        - name: ui-app
          image: ashu20150/uifrontendaws:1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ui-app
spec:
  type: LoadBalancer
  selector:
    app: ui-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
