apiVersion: v1
kind: Service
metadata:
  name: microservice-app-service
spec:
  selector:
    app: microservice-app
  ports:
    - name: microservice1-http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: microservice2-http
      protocol: TCP
      port: 82
      targetPort: 8082
  type: LoadBalancer
