apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: microservice1-http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: microservice2-http
      protocol: TCP
      port: 82
      targetPort: 8082
  type: {{ .Values.serviceType }}

