version: '3.8'
services:
  backend2:
    container_name: microservice2LinuxContainer
    platform: linux/amd64
    build:
      context: C:\Users\ashut\Desktop\Projects\DEVOPS\Microservice2
    ports:
      - "8083:8082"
    networks:
      - app-network
    environment:
     - SPRING_PROFILES_ACTIVE=dev

  backend1:
    container_name: microservice1LinuxContainer
    platform: linux/amd64
    build:
      context: C:\Users\ashut\Desktop\Projects\DEVOPS\Microservice1
    ports:
      - "8081:8080"
    networks:
      - app-network
    environment:
      - BASEURL_MICROSERVICE2=http://microservice2LinuxContainer:8082/
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - backend2
  frontend:
    container_name: frontend
    platform: linux/amd64
    build:
      context: C:\Users\ashut\Desktop\Projects\DEVOPS\uiservice
      args:
       REACT_APP_MICROSERVICE1_API_BASE_URL: http://localhost:8081
       REACT_APP_MICROSERVICE2_API_BASE_URL: http://localhost:8083
    ports:
      - "3001:3000"
    networks:
      - app-network
    depends_on:
      - backend1
      - backend2
    environment:
      - CHOKIDAR_USEPOLLING=true  # Optional: for live reload in Docker on Windows/macOS

networks:
  app-network:
    driver: bridge
