version: '3.8'
services:
  frontend:
    container_name: frontendForAws
    platform: linux/amd64
    image: uifrontendaws:1
    build:
      context: C:\Users\ashut\Desktop\Projects\DEVOPS\uiservice
      args:
       REACT_APP_MICROSERVICE1_API_BASE_URL: http://a1a921215d8ec4e22b5caf46ac90b6d7-1647125316.us-west-2.elb.amazonaws.com
       REACT_APP_MICROSERVICE2_API_BASE_URL: http://a1a921215d8ec4e22b5caf46ac90b6d7-1647125316.us-west-2.elb.amazonaws.com:82
    ports:
      - "3001:3000"
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true  # Optional: for live reload in Docker on Windows/macOS

networks:
  app-network:
    driver: bridge
