apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: microservice1
          image: {{ .Values.microservice1.image }}
          ports:
            - containerPort: 8080
          env:
            - name: BASEURL_MICROSERVICE2
              value: {{ .Values.microservice1.baseUrl }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.springProfile }}
        - name: microservice2
          image: {{ .Values.microservice2.image }}
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.springProfile }}
