apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
   type: {{ .Values.serviceType }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000